version: '2'
services:
  app:
    build: .
    image: infoamazonia/desmatamento
    volumes:
      - ./:/home/node/app:delegated
    ports:
     - 3002:8000
    restart: always
    networks:
      - default
      - weblan

networks:
 weblan:
   external:
    name: ispconfig_weblan